UnivGPT/univgpt_fe

src/App.js, src/index.css, src/routes/InfoCheck.jsx
=> infocheck page edit input-b added

src/components/Header/Header.css, src/components/Prompts/index.jsx, src/components/SideBar/index.jsx, src/index.css, src/routes/HomePage.jsx, src/routes/InfoCheck.jsx, src/routes/MyPage.jsx, src/routes/PromptDetailPage.jsx, src/routes/SignInPage.jsx, src/routes/SignUpPage.jsx, tailwind.config.js
(1) gpt-green 이라는 이름으로 custom color 만들었슴다. 형광옥색을 6FCACD 색으로 쫙 바꿨는데 텍스트나 hover는 그대로 형광옥색인 편이 가독성이나 디자인 면에서 더 좋은 것 같아서 놔뒀어유
(2) 버튼을 길쭉이 버튼(button-a)과 홀쭉이 버튼(button-b), 태그 대신 쓰는 버튼, 각종 색깔 버튼 등등으로 구분했슴다! 지우 코드에서도 내가 찾은만큼은 다 바꿔놨는데 conflict 일어나도 놀라지 마유!
(3) homepage, mypage랑 sidebar 디자인 조금 바꿨는데 함 보고 맘에 들면 반영해유!
(4) promptdetailpage의 디자인을 완성했슴다
=> feat:custom color, button design change

src/components/Comments/commentElement.jsx, src/components/Comments/index.jsx, src/components/SideBar/index.jsx, src/routes/PromptDetailPage.jsx, src/routes/SignInPage.jsx
1. 구글 로고로 로그인 바꿈
2. 프롬프트 상세페이지 사이드바 디자인 변경
=> [feat] google logo

src/routes/PromptMakePage.jsx
=> feat: promptmakepage

src/data/category.js, src/data/prompts.js, src/routes/HomePage.jsx, src/routes/PromptMakePage.jsx
카테고리 필터링 구현 중
더미데이터 활용
프롬프트메이크페이지 컨플릭트 예상
=> category filtering(1/2)

src/routes/HomePage.jsx
카테고리로 필터링하는거 구현 완!!
그리고 검색도 다시 제목 검색하는걸로 바꿔놨어용
=> [feat] category filter

README.md, src/components/SideBar/index.jsx, src/index.css, src/routes/InfoEditPage.jsx, src/routes/MyPage.jsx, src/routes/PromptDetailPage.jsx, src/routes/PromptMakePage.jsx
(1) 카테고리 복수선택 가능한 체크박스 형태로 구현
(2) '입력값추가' 버튼 위치 변경
(3) 쓰레기통 위치 변경 및 input css 조정
(4) 미리보기/삭제/게시 버튼 css 수정
(5) 도움말 버튼 추가
=> fix:promptMakePage

src/routes/HomePage.jsx, src/routes/PromptDetailPage.jsx
=> fix:promptDetailPage size

src/routes/HomePage.jsx, src/routes/PromptMakePage.jsx
=> fix: user guide

src/components/Modal/index.jsx, src/components/SideBar/index.jsx, src/index.css, src/routes/HomePage.jsx, src/routes/PromptMakePage.jsx
- 프롬프트 메이크 페이지에 미리보기 버튼 클릭 시 프롬프트 디테일 페이지와 같은 모달 -> 보내기 버튼 클릭 시 챗지피티에게 보내는 화면 모달 노출
- 현재 "X" 클릭 시 모달 제거
=> promptMakePage Modal(1/2)

src/components/Comments/commentElement.jsx, src/components/Comments/index.jsx, src/components/SideBar/index.jsx
- literally... 초기 좋아요 여부까지 모두 반영되게 해 보았어요
- 이제 자기가 쓴 comment면 삭제 버튼이 뜹니당
=> fix: promptSideBar에도 좋아요 색깔 반영되게 변경

src/components/Header/index.jsx, src/components/Modal/index.jsx, src/components/Prompts/index.jsx, src/components/SideBar/index.jsx, src/routes/MyPage.jsx, src/routes/PromptMakePage.jsx
1. promptMakeModal 컴포넌트 연결
2. 마이페이지 유저, 프롬프트 연결
3. 마이페이지 나의 프롬프트, 스크랩한 프롬프트 필터링 완료
4. like 하트에 cursor-pointer 추가
=> pormptMakeModal 연결, 마이페이지 유저 연결 및 프롬프트 필터링

src/api/api.js, src/routes/InfoEditPage.jsx
회원 정보 수정에서 비밀번호 변경 시 로그아웃된 상태로 홈화면으로 이동, 
회원 정보 수정 취소하면 mypage로 이동
=> fix: infoedit page

src/components/SideBar/index.jsx, src/routes/HomePage.jsx
=> sidebar username 관련

src/components/Comments/commentElement.jsx, src/components/Comments/index.jsx, src/components/SideBar/index.jsx, src/index.css, src/routes/HomePage.jsx, src/routes/InfoCheck.jsx, src/routes/InfoEditPage.jsx, src/routes/MyPage.jsx, src/routes/PromptDetailPage.jsx, src/routes/PromptMakePage.jsx
1. 버튼 기능 없는 박스 중 hover action 있는 것들 해제
2. homepage, promptmakepage, promptdetailpage, mypage 등에 커스텀 사이드바 구현
3. promptDetialPage 사이드바 및 댓글 컴포넌트 디자인/아이콘 수정
=> fix: sidebar design, custom scroll bar

src/routes/PromptEditPage.jsx, src/routes/PromptMakePage.jsx
create: promptedit page 만드는중, 에러 있는 상태. conflict 없을 것 같아서 보내놓기만 합니당
=> create: promptedit page 만드는중, 에러 있는 상태

src/components/Modal/index.jsx, src/routes/PromptMakePage.jsx
1. promptMakePage 모달 (객관식 제외)
2. 카테고리 선택 스크롤바 (카테고리 박스 자제 크기 조정 필요할 듯)
=> promptMakeModal(without select)

src/components/Comments/commentElement.jsx, src/components/Comments/index.jsx, src/components/Header/index.jsx, src/components/SideBar/index.jsx, src/index.css
(1) 로그인/로그아웃시 헤더 디자인 다른 부분 수정
(2) 사이드바에서 스크랩 on/off시 레이아웃 다른 것 수정
(3) 프롬프트 정보 란 디자인 수정
(4) 댓글창 스크롤 이슈 해결
(5)댓글창 레이아웃 조정
=> fox:promptSidebar & header

src/components/Modal/index.jsx, src/index.css, src/routes/PromptDetailPage.jsx, src/routes/PromptMakePage.jsx
1. promptmakemodal 미리보기 데이터 받아오기
2. promptMake 모달 닫기 표시 디자인 수정
=> promptMakeModal

src/components/SideBar/index.jsx, src/routes/HomePage.jsx
1. smallprompt 사이드바에서 뷰 순으로 받아올 수 있도록!
=> [feat] smallprompt_orderedView

src/components/Prompts/index.jsx, src/components/SideBar/index.jsx, src/routes/HomePage.jsx
=> fix:homepage sidebar

src/api/api.js
일반 로그인했을 때 비밀번호 잘못 입력했을 시 에러 화면 안 뜨게 하기
=> fix: fix login error

src/components/Mentions/defaultStyle.js, src/components/Modal/index.jsx, src/components/Prompts/index.jsx, src/index.css, src/routes/PromptMakePage.jsx
=> fix: promptMakePage & modal
